// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/lithosai.json" with { type: "json" };
import { flattenChatModelCatalog, flattenClassifierModelCatalog, flattenImageModelCatalog, type ChatModelCatalog, type ClassifierModelCatalog, type ImageModelCatalog } from "../model-catalog.ts";

export const LITHOSAI_MODELS: ChatModelCatalog<typeof values, "lithosai"> =
	flattenChatModelCatalog("lithosai", values);

export const LITHOSAI_IMAGE_MODELS: ImageModelCatalog<typeof values, "lithosai"> =
	flattenImageModelCatalog("lithosai", values);

export const LITHOSAI_CLASSIFIER_MODELS: ClassifierModelCatalog<typeof values, "lithosai"> =
	flattenClassifierModelCatalog("lithosai", values);
